name: "Deploy to github pages"

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: sudo apt install fonts-noto-cjk fonts-noto-color-emoji
      - run: npm ci

      - run: npm run presentation:build
      - run: npm run presentation:pdf
      - uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: slide.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          allowUpdates: true

      - run: REMOTE_URL=https://chelproc.github.io/20210715-coral-react-lt/ npm run build
      - run: touch dist/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
